### ISSUE TITLE
incomplete TCA Konfiguration on the carousel tce

### ISSUE THREAD

**Issue by cosmox** [Ecodev/typo3-cms-speciality-distribution#104]
There are three options to select a content element as slider item, in the Backend but:
There are four items in the TCA types array, but the first item "1" is not avaiable in the Backend! 
The Item "textandimage" dont show any "bodytext" or "color select" field in the Backend, because there is no configuration for this fields in this file:

typo3conf/ext/bootstrap_package/Configuration/TCA/CarouselItem.php

**Comment by fabarea** [comment]
It looks to me this bug report belongs to another repository and not speciality_distribution.

**Comment by cosmox** [comment]
sorry that was totally the wrong repo :)
