### ISSUE TITLE
how to edit print layout

### ISSUE THREAD

**Issue by aPollO2k** [Ecodev/typo3-cms-speciality-distribution#105]
hello,

i only want to know how to edit the layout for print the page? for example there are some menus and hyperlinks in the print layout i want to remove. but i can't find a print.css or somethink like else.

where is defined what is shown and what is hidden in the printed version? i mean the browsers build-in print function. i hope you guys know what i mean.

i want to remove the highlighted objects.
![print_remove](https://cloud.githubusercontent.com/assets/5796295/4151550/146adf0e-3447-11e4-929b-1f27409237fc.png)
![print_remove2](https://cloud.githubusercontent.com/assets/5796295/4151551/146bd6a2-3447-11e4-8912-79c24c21f74c.png)
![print_remove3](https://cloud.githubusercontent.com/assets/5796295/4151549/146a6542-3447-11e4-84dc-a2857ca64cd6.png)

greets
Chris

**Comment by fabarea** [comment]
Should be added in a custom CSS file which overlays Bootstrap.
