### ISSUE TITLE
can't insert new content / BE content bad position

### ISSUE THREAD

**Issue by gilas1959** [Ecodev/typo3-cms-speciality-distribution#108]
I have correctly installed your +ext using composer then login into the BE.
If I attempt to create a news text only CE, it is saved correctly but it is not displayed into the FE.
I saved the record after a Text/Images CE (there is some issues here).
The text only CE is not hidden; maybe your +ext shows only the first record found.
The record inserted was after a Text/Images CE. I change the order (drag 'n'drop) and put it in first position in the same column and it is displayed correctly. Then I put it again in the 3rd position, after a Text/Images CE. Now the order displayed in the FE doesnt' respect the order of the BE; I found the record always in the first position (?). 
This happens in page uid=42 (named: Text and Images).
Howevere all the images are not displayed into the FE; I checked for GDLib, ImageMagick and all is OK (test are achieved correctly).
thank you

ALEX

**Comment by fabarea** [comment]
I was not able to reproduce this error.
