### ISSUE TITLE
how to include static template (for extensions)

### ISSUE THREAD

**Issue by sombradelviento** [Ecodev/typo3-cms-speciality-distribution#116]
Hi,

I'm pretty new to typo3 bootstrap so pls forgive my (probably) stupid questions. I'm trying to utilize bcgooglemaps in my project to display google maps in the FE. However, encountered dificulties adding the nececary static template to the root template because the include sections is missing. 
Is there a way to inlude the static template (bcgooglemaps) to the template via typoscript? 
I also discovered that if I add plain html (via special elements in page edit) frontend stays blank... 

appreciate your response(s)

**Comment by fabarea** [comment]
Should be done via Static File for a new extension as follows http://docs.typo3.org/typo3cms/extensions/t3colorbox/ExtensionInstallSetup/Index.html
