### ISSUE TITLE
Check "Uses case sensitive identifiers" to defaut File Storage

### ISSUE THREAD

**Issue by kaolol** [Ecodev/typo3-cms-speciality-distribution#118]
Et oui, merci le FAL...

File Storage need to have
"Uses case sensitive identifiers" 
checked
Otherwise, it leads to error when uploading a file with...uppercase ;)
Would il be possible to update Speciality_Distribution ?

Merci,
Et toujours bluffé par la qualit e vos contributions.
TYPO3 level up !
;)
All the best,
Laurent

**Comment by fabarea** [comment]
It will be fixed on the next dump / TER upload.
