### ISSUE TITLE
Improve site title ?

### ISSUE THREAD

**Issue by kaolol** [Ecodev/typo3-cms-speciality-distribution#119]
The site title is not really beautiful... ;)
"Speciality Distribution: Page title"
No space after site title, space before page title.

This TS make it  better 
# Site title
config.pageTitleSeparator = -
config.pageTitleSeparator.noTrimWrap = |  |  |

"Speciality Distribution - Page title"

Do you think you could integrate that ?
I guess i could do it, If you tell me how ;) 

All the best,  !
Laurent

**Comment by fabarea** [comment]
You can make a PR following:

* Fork this repo https://github.com/Ecodev/speciality
* Update the config https://github.com/Ecodev/speciality/blob/master/Configuration/TypoScript/Config/config.ts

Can you check if we could use this VH ``v:page.header.title``
https://fluidtypo3.org/viewhelpers/vhs/master/Page/Header/TitleViewHelper.html

**Comment by kaolol** [comment]
Hi !
Pull request done ! ;)
If it would better via VHS, I ready to try..
But I don't know where to put this VHS v:page.header.title
I tried to add it to
https://github.com/Ecodev/speciality/blob/master/Resources/Private/Layouts/Page.html

But it doesn't display.
Where should it put it ?
All the best,
Laurent

**Comment by fabarea** [comment]
Solved in other PR
