### ISSUE TITLE
Content added in a bootstrap Column Row container only visible with the List View of TYPO3 backend (not visible with module page)

### ISSUE THREAD

**Issue by vincentkollebolle** [Ecodev/typo3-cms-speciality-distribution#121]
TYPO3 6.2
Speciality 1.0.0
DCE 1.0.4

Hi everybody.
DCE extension became recently for me a must have and I use it for almost every Website I have to do. I also use the extension Speciality Distribution (speciality_distribution, 1.0.0) really good to to kickstart a TYPO3 project with twitter bootstrap.

I realise that there is a small problem when we use the both extension together.
Speciality allow you to create a Bootstrap Column/Row content 
If I insert a DCE inside a Speciality Bootstrap Column/Row content type (with the view Page of the TYPO3 backend), the content doesn't appear inside the columns. It is created, but is visible only with the view List of TYPO3 backend.

WORKAROUND for those in peril :
Use this small workaround.
1./Create the DCE with the module/view Page of the backend (it will not appear),
2./Go to the module View of the backend on the same page.
3./Look for the DCE and cut it.
4./Go back to module Page of TYPO3 on the same page. Past it where you want.
You've done it !

Question : is this a problem with speciality or with the DCE ? No idea, i just wanted to help by reporting my workaround. If you have an idea of what to do to solve the problem, tell me i'll help if i can.

**Comment by vincentkollebolle** [comment]
I also reported this issue to the DCE developper team 
https://forge.typo3.org/issues/70153

**Comment by fabarea** [comment]
Thanks for your report / notes. I may help other people. Perhaps the issue has been settled with TYPO3 7 LTS meanwhile. Let hope...
