### ISSUE TITLE
Spéciality Distribution with TYPO3-7.6.0 ? 

### ISSUE THREAD

**Issue by vincentkollebolle** [Ecodev/typo3-cms-speciality-distribution#122]
Ola ecodev team ! 
Juste a small question is the whole new TYPO3 compatible with speciality_distribution? 
The install procedure on github explain how do install for TYPO3-6.4.2 but is the same to install it on typo3-7 ? 

Can't wait to test it with the new backend ! 
Happy to reports bug if needed ! (can't do many other stuff yet, beginner level)

**Comment by fabarea** [comment]
Knowns bug [EXT:fluidbootstraptheme](https://github.com/bootstraptheme-for-typo3/fluidbootstraptheme) is not yet compatible with 7 LTS
