### ISSUE TITLE
icon_color, icon_background don't display in Backend by Text with Icon

### ISSUE THREAD

**Issue by paulsen-it** [Ecodev/typo3-cms-speciality-distribution#125]
Hello Together,
I have Typo 3 7.6.x installed with bootstrap_package. When I want to use Text with Icon the Icon have everytime the Background 333333 and color FFFFFF. This Values are saved in the Database, and I cannot change this Values in the Backend. I look and found that both should shown in the Dataset, next to Icon Position. But they are not there. Why?
Thank you for any help

**Comment by PowerKiKi** [comment]
Looks very obsolete, closing
