### ISSUE TITLE
VERY long page load time for the first request on every page

### ISSUE THREAD

**Issue by apiening** [Ecodev/typo3-cms-speciality-distribution#54]
Hi bootstrap package users!

I have a strange issue with the performance: Every page I visit for the first time has a very long load time. I measured between 17 and 72 seconds for a page-load with the developer tools of google chrome. The time is almost completely spent on the first get with the page url, from there it takes a fraction of a second to load all following requests. So I think the delay happens completely due to php processing in some way.

However, every following request has a load time of roughly 250ms which feels like the page is popping up without any noticeable delay. This is true for every single page I checked. However, this is not only because of local browser caching, I can load the page from another browser which has never seen this page before and it is just about 50 to 100ms slower but still blazingly fast.

I have installed APC as PHP opcode cacher and raised the memory limit in PHP and followed the performance guide but it only made every request but the first one even faster. I really understand that typo3 does internal caching so it's completely ok that the first request takes longer to build up the cache and create indexed search entries and whatsoever but the server has plenty of power and almost no load while I'm testing this and I never reached load times that high before.

I have another Typo3 install on the very same machine. It is a version 4.5.3 so not directly comparable but even with cleared cashes I barely get over 1,5 seconds of load time, even for a page with some images.

I can't tell if this is a general typo3 issue or one specifically related to the bootstrap starter package configuration so I decided to ask if someone here ever had an experience like this?

I don't know how I can dig any further into that, maybe there is just a configuration issue I can't think of causing this behavior.

Any help is greatly appreciated!

Thank you in advance!

Andreas

**Comment by fabarea** [comment]
Should be fixed by now.
