### ISSUE TITLE
Bootstrap: Element Carousel does not allow images

### ISSUE THREAD

**Issue by AdvanceWM** [Ecodev/typo3-cms-speciality-distribution#65]
Even an Admin user cannot add images to the Bootstrap: Element Carousel when it is used as a content element on a page. This is not the same issue as #64, as this involves admin users.

Images can be added to image-only elements, but not the Element Carousel.

(I do not know if this belongs here, or under fluidcontent_bootstrap.)

**Comment by fabarea** [comment]
Extension has been updated so perhaps there is the chance the problem has been fixed. Distribution can be installed via the Extension Manager just after a fresh install.
