### ISSUE TITLE
[FEATURE] Switch to separate CSS files in SharedResources.html

### ISSUE THREAD

**Issue by webian** [Ecodev/typo3-cms-speciality-distribution#71]
In EXT:speciality/Resources/Private/Partials/SharedResources.html the CSS files are merged together if *standalone="true"* is not specified for each asset.
That's good to minimize HTTP requests but it's uncomfortable when developing CSS while inspecting the HTML cause it's hard to find out in which file a CSS rule is.

A quick switch could be useful in this case instead of editing 'SharedResources.html' each time.
I would like to implement it in some way so it could be merged in this project, but I don't know what could be the best way.
Do you have any hint? :)

Thanks!

**Comment by fabarea** [comment]
Still valid issue. Let me integrate in a way or another a debug flag as you suggest.

**Comment by fabarea** [comment]
While developing you can now switch to the decompressed version and vise versa, simply change "site.min.js" by "site.js".

```
EXT:speciality/Configuration/TypoScript/Plugin/tx_vhs.ts
```

The most easiest way to add a new asset (JS or CSS) is to open the file mentioned above and add a new section. To know more about managing your assets, refer to this blog article which addresses [Asset handling with FluidTYPO3](https://worksonmymachine.org/blog/asset-handling-with-fluidtypo3).
