### ISSUE TITLE
Empty carousel make module TYPO3 page inacessible

### ISSUE THREAD

**Issue by vincentkollebolle** [Ecodev/typo3-cms-speciality-distribution#74]
In a page, if I had a carousel with no content (0 image, 0 content, 0 text) and save and close. Then if I try to access the page again i'have got the following message

<< Oops, an error occurred!

The argument "each" was registered with type "array", but is of type "string" in view helper "TYPO3\CMS\Fluid\ViewHelpers\ForViewHelper"

More information regarding this error might be available online. >>

Workaround founded : use the module web > list to delete the incrimined content

**Comment by fabarea** [comment]
Should be fixed with latest version.
