### ISSUE TITLE
main.css: space over main block elements

### ISSUE THREAD

**Issue by webian** [Ecodev/typo3-cms-speciality-distribution#77]
Hi,
in main.css there is this rule:
```
/* Give room to main block elements for anchor links */
aside[role=complementary] > div.csc-default,
div[role=section] > div.csc-default{
	padding-top: 30px;
}
```

It gives a lot of space over main block elements and I can't understand the reason since anchor links are at the end of H1.
Please can you help me to understand?
Thanks!

**Comment by fabarea** [comment]
Not using any more EXT:css_styled_content. It has been replaced by EXT:fluidcontenet_core
