### ISSUE TITLE
vhs assets caching problem

### ISSUE THREAD

**Issue by braguzz** [Ecodev/typo3-cms-speciality-distribution#86]
I have a problem in vhs assets

sometimes when I flush the cache, vhs asset system is non able to rebuid the right things and the result is no cache and no css.

(sometimes only some css or some css missing)

in apache log I have a list of
...
File does not exist: /data/www/bootstrap_package/htdocs/typo3temp/vhs-assets-fontawesome.css
File does not exist: /data/www/bootstrap_package/htdocs/typo3temp/vhs-assets-bootstrap-core-jquery-colorbox-jquery-colorbox-main-plugin-main-jquery.flexslider-min-JavaScriptforNews-SliderCE-992.js
...
and checking filesystem files aren't there.

reflushing the cache 99% problem disappare.

what can I check?

(fudriot gives me a workaround https://github.com/Ecodev/bootstrap_package#frontend-development-workflow but I did not understand much of it..)

switching to standard inclusion?
page.includeCSS

please help!

**Comment by fabarea** [comment]
Performance problem should be fixed by the time.
