### ISSUE TITLE
Duplicate content with same Id in Page module

### ISSUE THREAD

**Issue by pilouf** [Ecodev/typo3-cms-speciality-distribution#89]
Hi,

I have some problems with bootstrap contents. I uninstall fluidcontent_bootstrap and then reinstall it, same thing for EXT flux and then : All my content inside Bootstrap Column Row are "duplicated" outside this content but with the same uid !

![duplicate_content](https://f.cloud.github.com/assets/6884937/2358928/eb1ad26c-a611-11e3-987b-4378bd65886c.png)

Do you know how to fix it ?

**Comment by fabarea** [comment]
Should be fixed by the time.
